name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create google-services.json
      run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > $GITHUB_WORKSPACE/app/google-services.json

    - name: Clean Bulid
      run: ./gradlew clean

    - name: Create Local Properties
      run: |
        echo "signalingServer=${{ secrets.SIGNALING_SERVER }}" >> local.properties
        echo "turnServer=${{ secrets.TURN_SERVER }}" >> local.properties
        echo "turnServerUserName=${{ secrets.TURN_SERVER_USERNAME }}" >> local.properties
        echo "turnServerUserPassword=${{ secrets.TURN_SERVER_USER_PASSWORD }}" >> local.properties

    - name: Run Unit Test
      run: ./gradlew test
      
    - name: Run Android Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
       api-level: 29
       target: default
       arch: x86_64
       profile: Nexus 6
       script: ./gradlew connectedCheck --stacktrace --no-daemon
       timeout-minutes: 30
       
    - name: Assemble
      run: ./gradlew assemble
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
       name: debug
       path: ./app/build/outputs/apk/debug/app-debug.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
       name: release
       path: ./app/build/outputs/apk/release/app-release-unsigned.apk
